pipeline{
    agent any

    tools {
         maven 'maven'
         jdk 'java'
    }

    stages{
        stage('checkout'){
            steps{
                checkout([$class: 'GitSCM', branches: [[name: 'jenkins-demo']], extensions: [], userRemoteConfigs: [[credentialsId: 'github access', url: 'https://github.com/ruhishinde/java-jenkins-test.git']]])
            }
        }
        stage('build'){
            steps{
               bat 'mvn package'
            }
        }
    }
}